name: Build on merge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    env:
      GOOS: "linux"
      GOARCH: "amd64"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o sumo-linux-amd64
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: sumo-linux-amd64
        path: ./sumo-linux-amd64
